apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-sender
spec:
  selector:
    matchLabels:
      app: message-sender
  replicas: 2
  template:
    metadata:
      labels:
        app: message-sender
    spec:
      containers:
        - name: message-sender
          image: deenayn/message-sender
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: message-sender-svc
spec:
  selector:
    app: message-sender
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
---
