spring:
  application:
    name: Message Validator
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
